namespace DysonSphereProgramCalculator;

public enum Item
{
    IronOre,
    CopperOre,
    Stone,
    Coal,
    SiliconOre,
    TitaniumOre,
    Water,
    Hydrogen,
    IronIngot,
    CopperIngot,
    EnergeticGraphite,
    HighPuritySilicon,
    TitaniumIngot,
    SulfuricAcid,
    Magnet,
    MagneticCoil,
    Glass,
    TitaniumAlloy,
    Graphene,
    OpticalGraftingCrystal,
    Steel,
    CircuitBoard,
    ElectricMotor,
    MicrocrystallineComponent,
    CasimirCrystal,
    CarbonNanotube,
    StalagmiteCrystal,
    Gear,
    ElectromagneticTurbine,
    Processor,
    SuperMagneticRing,
    TitaniumGlass,
    PlaneFilter,
    QuantumChip,
    FrameMaterial,

    AdvancedMiningMachine,
    PlaneSmelter,
    AssemblerMk3,
    QuantumChemicalPlant
}